<a href="https://colab.research.google.com/github/Suyoung-Min/Pytorch-Tutorial/blob/main/Tutorial/nn.ModuleMLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn
#model = nn.Linear(input_dim, output_dim)
import torch.nn.functional as F
#cost = F.mse_loss(prediction, y_train)


In [11]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [12]:
model = nn.Linear(3,1)

In [13]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.3122,  0.1610,  0.0932]], requires_grad=True), Parameter containing:
tensor([-0.1670], requires_grad=True)]


In [15]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

nb_epochs = 3000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/3000 Cost: 2.262633
Epoch  100/3000 Cost: 2.169984
Epoch  200/3000 Cost: 2.082118
Epoch  300/3000 Cost: 1.998820
Epoch  400/3000 Cost: 1.919815
Epoch  500/3000 Cost: 1.844901
Epoch  600/3000 Cost: 1.773868
Epoch  700/3000 Cost: 1.706465
Epoch  800/3000 Cost: 1.642563
Epoch  900/3000 Cost: 1.581950
Epoch 1000/3000 Cost: 1.524443
Epoch 1100/3000 Cost: 1.469883
Epoch 1200/3000 Cost: 1.418138
Epoch 1300/3000 Cost: 1.369021
Epoch 1400/3000 Cost: 1.322424
Epoch 1500/3000 Cost: 1.278201
Epoch 1600/3000 Cost: 1.236229
Epoch 1700/3000 Cost: 1.196397
Epoch 1800/3000 Cost: 1.158597
Epoch 1900/3000 Cost: 1.122691
Epoch 2000/3000 Cost: 1.088611
Epoch 2100/3000 Cost: 1.056241
Epoch 2200/3000 Cost: 1.025510
Epoch 2300/3000 Cost: 0.996316
Epoch 2400/3000 Cost: 0.968592
Epoch 2500/3000 Cost: 0.942248
Epoch 2600/3000 Cost: 0.917233
Epoch 2700/3000 Cost: 0.893439
Epoch 2800/3000 Cost: 0.870834
Epoch 2900/3000 Cost: 0.849352
Epoch 3000/3000 Cost: 0.828917


In [19]:
ex_x = torch.FloatTensor([[73, 80, 75],
                          [1,2,3]])
print(model(ex_x))

tensor([[151.8530],
        [  3.9887]], grad_fn=<AddmmBackward0>)


In [20]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.6906, 0.5136, 0.8066]], requires_grad=True), Parameter containing:
tensor([-0.1490], requires_grad=True)]
