<a href="https://colab.research.google.com/github/Suyoung-Min/Pytorch-Tutorial/blob/main/Tutorial/nn.ModuleLR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn
#model = nn.Linear(input_dim, output_dim)
import torch.nn.functional as F
#cost = F.mse_loss(prediction, y_train)


In [5]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [6]:
model = nn.Linear(1,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[-0.6932]], requires_grad=True), Parameter containing:
tensor([0.7269], requires_grad=True)]


In [7]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [8]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 26.546532
Epoch  100/2000 Cost: 0.227431
Epoch  200/2000 Cost: 0.140538
Epoch  300/2000 Cost: 0.086844
Epoch  400/2000 Cost: 0.053664
Epoch  500/2000 Cost: 0.033161
Epoch  600/2000 Cost: 0.020492
Epoch  700/2000 Cost: 0.012663
Epoch  800/2000 Cost: 0.007825
Epoch  900/2000 Cost: 0.004835
Epoch 1000/2000 Cost: 0.002988
Epoch 1100/2000 Cost: 0.001846
Epoch 1200/2000 Cost: 0.001141
Epoch 1300/2000 Cost: 0.000705
Epoch 1400/2000 Cost: 0.000436
Epoch 1500/2000 Cost: 0.000269
Epoch 1600/2000 Cost: 0.000166
Epoch 1700/2000 Cost: 0.000103
Epoch 1800/2000 Cost: 0.000064
Epoch 1900/2000 Cost: 0.000039
Epoch 2000/2000 Cost: 0.000024


In [9]:
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var)
print(f"4의 예측값: {pred_y}")

4의 예측값: tensor([[7.9901]], grad_fn=<AddmmBackward0>)


In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9943]], requires_grad=True), Parameter containing:
tensor([0.0130], requires_grad=True)]
